/* MODELAGEM BÁSICA - ENTIDADE = TABELA*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTERE(30)
TELEFONE - CARACTERE(30)
ENDERECO - CARACTERE(100)
SEXO - CARACTERE(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA/AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	CPF INT(11),
	EMAIL VARCHAR(30),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),
	SEXO CHAR(1)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES; -- ONLY MYSQL 

/* EXIBINDO A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BÁSICA DA INSERÇÃO - INSERT INTO TABELA... */

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES ("MIGUEL",123456789,"MIGUEL@TESTE.COM","99123456","MARCOLINO SIMOES FERREIRA - ITAMARATI - PETROPOLIS - RJ","M");

INSERT INTO CLIENTE VALUES ("BENTO",234567891,"BENTO@TESTE.COM","99123456","MARCOLINO SIMOES FERREIRA - ITAMARATI - PETROPOLIS - RJ","M");

INSERT INTO CLIENTE VALUES ("CLARA",345678912,"CLARA@TESTE.COM","99123456","MARCOLINO SIMOES FERREIRA - ITAMARATI - PETROPOLIS - RJ","F");

/* FORMA 02 - EMITINDO AS COLUNAS */

INSERT INTO CLIENTE (NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES ("JENI","F","MARCOLINO SIMOES FERREIRA - ITAMARATI - PETROPOLIS - RJ","99345678",456789123);

/* FORMA 03 - INSERT COMPACT - SOMENT NO MYSQL */

INSERT INTO CLIENTE VALUES("TERESA",567891234,"TERESA@TESTE.COM","99123456","MARCOLINO SIMOES FERREIRA - ITAMARATI - PETROPOLIS - RJ","F"),
("AFONSO",678912345,"AFONSO@TESTE.COM","99123456","MARCOLINO SIMOES FERREIRA - ITAMARATI - PETROPOLIS - RJ","M");

/* O COMANDO SELECT 
selecao projecao e juncao
*/

SELECT NOW() as DATA_HORA, 'MIGUEL MILAGRES' AS ALUNO;

SELECT 'MIGUEL MILAGRES';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADÊMICOS */

SELECT * FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = "MARCOLINO SIMOES FERREIRA - ITAMARATI - PETROPOLIS - RJ";

/* UTILIZANDO O LIKE */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO FROM CLIENTE
WHERE TELEFONE LIKE '9912%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE EMAIL LIKE '%TESTE%';

/* RESOLVENDO EXERCÍCIO LIVRARIA */

CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS (
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	UF CHAR(2),
	ANO INT(4)
);

INSERT INTO LIVROS
VALUES 	('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009),
		('SQL para leigos','João Nunes','M',450,'Addison',98,'SP',2018),
		('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008),
		('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78.99,'RJ',2018),
		('Habitos Saudáveis','Eduardo Santos','M',630,'Beta',150.98,'RJ',2019),
		('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016),
		('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015),
		('Pra sempre amigas','Leda Silva','F',510,'Insignia',78.98,'ES',2011),
		('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130.98,'RS',2018),
		('O poder da mente','Clara Mafra','F',120,'Continental',56.58,'SP',2017);

SELECT * FROM LIVROS; 

SELECT LIVRO, EDITORA FROM LIVROS; 

SELECT LIVRO, UF FROM LIVROS
WHERE SEXO = 'M'; 

SELECT LIVRO, PAGINAS FROM LIVROS
WHERE SEXO = 'F'; 

SELECT VALOR FROM LIVROS
WHERE UF = 'SP';

SELECT AUTOR FROM LIVROS
WHERE (SEXO = 'M') AND (UF = 'SP' OR UF = 'RJ'); 
